TARGETS=cmd_image.sh \
	cmd_image_prune.sh \
	cmd_instance_prune.sh \
	create_forge.sh \
	network.sh \
	stage_bootstrap_build.sh \
	stage_build.sh \
	stage_commit.sh \
	stage_launch.sh \
	stage_launch_cleanup.sh

dummy:

install:
	install -m 0555 $(TARGETS) $(DESTDIR)/lib
